module.exports = {
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  COPY_GIF_URL_REQUEST: 'COPY_GIF_URL_REQUEST',
  COPY_GIF_URL_SUCCESS: 'COPY_GIF_URL_SUCCESS',
  FETCH_GIFS_REQUEST: 'FETCH_GIFS_REQUEST',
  FETCH_GIFS_SUCCESS: 'FETCH_GIFS_SUCCESS',
  FETCH_GIFS_FAILURE: 'FETCH_GIFS_FAILURE',
  ADD_GIF_TO_FAVORITES: 'ADD_GIF_TO_FAVORITES',
  REMOVE_GIF_FROM_FAVORITES: 'REMOVE_GIF_FROM_FAVORITES',
  FETCH_NEW_GIFS_PAGE_REQUEST: 'FETCH_NEW_GIFS_PAGE_REQUEST',
  FETCH_NEW_GIFS_PAGE_SUCCESS: 'FETCH_NEW_GIFS_PAGE_SUCCESS'
}
